spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    url: 'jdbc:postgresql://localhost:5432/claim-api'
    username: 'postgres'
    password: 'postgres'
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
security:
  config:
    password-flow: true
    authcode-flow: false
keycloak:
  auth-server-url: https://keycloak.yamakassi.ru
  realm: claimapi
  resource: claimapi
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
springdoc:
  api-docs:
    path: /api-docs

