spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    url: 'jdbc:postgresql://localhost:5432/claim-api'
    username: 'postgres'
    password: 'postgres'
    driverClassName: org.postgresql.Driver

  jpa:
    generate-ddl: true


    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none

#security:
#  config:
#    password-flow: true
#    authcode-flow: false
#keycloak:
#  auth-server-url: https://localhost:9090/auth
#  realm: "test"
#  resource: "test"
#  bearer-only: true